added memory option to submission scripts
rinikerlab/reeds pull request #54
Opened 2021-09-02 16:18 UTC by SalomeRonja

My jobs have been getting stuck in the queue on Euler for longer wait times recently. I know that Benjamin experienced the same issue. At the moment, we're reserving 1024*replicas*nmpi_per_replica MB of memory for every submitted job, which is the default for a job submitted to Euler. This results in our jobs getting submitted to the bigmem queue, even though we actually need much less memory in practice.

Example: for a production run of my 28 benzenes in water, I reserve 376'000.00 MB, the maximally used memory during the simulation is only 10'280 MB.

To reduce the amount of memory that's reserved for a job, I extended the option which already existed for steps a and b to the rest of the submission scripts. I also cleaned up and adapted the example pipeline accordingly.

2021-09-02 16:19 UTC, SalomeRonja commented
The example pipeline is still running at the moment, but once it's finished without any issues, we can merge this into the eoff rebalancing branch, if you're okay with the changes @SchroederB

2021-09-02 18:57 UTC, SalomeRonja commented
from my side, the merge is good to go :)

2021-09-03 13:01 UTC, SchroederB requested changes
First of all, thanks for adding the memory option!

I just found 2-3 function calls, where I think we do not pass all declared parameters, could you please check if this is true and add them quickly?  Otherwise I think this is ready to go!

2021-09-03 13:12 UTC, SalomeRonja commented on examples/template_RE_EDS_project/a_job_opt_states.py
> +  ene_ana_lib = ene_ana_lib
Yes, you're right... that must have gotten lost in the merge. I'll add the missing options back in! Thanks for noticing

2021-09-03 18:00 UTC, SchroederB approved these changes

2021-09-03 18:00 UTC, merged